name: CI Pokemon API

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    unit-tests:
        runs-on: ubuntu-latest
        container: node:22
        steps:
            - uses: actions/checkout@v4
            - run: npm install
            - run: npx jest __tests__/unit.test.js
            - name: Save unit test artifact
              run: mkdir -p test-results && cp -r __tests__ test-results/
            - uses: actions/upload-artifact@v4
              with:
                name: unit-test-artifact
                path: test-results
                retention-days: 7

    integration-tests:
        needs: unit-tests
        runs-on: self-hosted
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: 22
            - run: npm install
            - uses: actions/download-artifact@v4
              with:
                name: unit-test-artifact
                path: downloaded-tests
            - run: npx jest __tests__/integration.test.js