name: CI Pokemon API

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    build-cloud:
        runs-on: ubuntu-latest

        container:
            image: node:22
        
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm install
            
            - name: Run tests
              run: npm test

    build-local:
        runs-on: self-hosted
    
        steps:
            - uses: actions/checkout@v4


            - name: Show API version
              run: echo "API Version is ${{ vars.API_VERSION }}"

            - name: Use API KEY
              run: |
                echo "Using secret API key in safe mode"
                # Le secret ne doit jamais être affiché directement
                node -e "console.logg('Secret length: ' + process.env.API_KEY.length)"
              env:
                API_KEY: ${{ secrets.API_KEY }}